### ISSUE TITLE
Double Click to ARM

### ISSUE THREAD

**Issue by nunofmds** [febalci/ha_pycrowipmodule#5]
Hi,

I need to double press for the ARM to succeed. When I press 1 time using HASSIO arm panel, the crow module beep 4 times with status arming but then it stops... I need to press again for it to arm.

Let me know if you need any debug logs and how should I do them.

Regards,
Nuno Silva

**Comment by nunofmds** [comment]
Using this repo -> https://github.com/acdcnow/ha_pycrowipmodule

**Comment by febalci** [comment]
Please discuss the issue in HA community forum
