### ISSUE TITLE
Error arming/disarming with Home Assistant version 2024.6 onwards

### ISSUE THREAD

**Issue by shadsnz** [febalci/ha_pycrowipmodule#6]
For reference in case anyone else finds this issue, trying to arm or disarm the alarm fails if you have a code in place, with error:

Failed to call service alarm_control_panel/alarm_arm_away. Validation error: Arming requires a code but none was given for alarm_control_panel.home

This has been discussed in 
[https://github.com/home-assistant/core/issues/118668](https://github.com/home-assistant/core/issues/118668)

And the issue can be fixed in ha_pycrowipmodule by adding the _attr_code_arm_required line (see below) into the alarm_control_panel.py file.

```
class CrowIPModuleAlarm(CrowIPModuleDevice, alarm.AlarmControlPanelEntity):
    """Representation of an Crow IP Module-based alarm panel."""
    _attr_code_arm_required = False
```

**Comment by febalci** [comment]
Fixed with v0.32
