### ISSUE TITLE
The version 79f273b for this integration can not be used with HACS.

### ISSUE THREAD

**Issue by nunofmds** [febalci/ha_pycrowipmodule#8]
Crow/AAP Alarm IP Module
Commit 79f273b will be downloaded

When downloaded, this will be located in '/config/custom_components/crowipmodule'
Remember that you need to restart Home Assistant before changes to integrations (custom_components) are applied.

The version 79f273b for this integration can not be used with HACS.

Installed version
e2dbd59
Latest version
79f273b

**Comment by dan-s-github** [comment]
according to #5 you are using the acdnow repo which includes hacs configuration. To install the version from this repo you need to remove the custom repo from hacs and then follow the installation instructions on the README

**Comment by febalci** [comment]
Added by pull request https://github.com/febalci/ha_pycrowipmodule/pull/9
